# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    container_name: db_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: db
    ports:
      - 9677:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 4574:8080