#index:
#    path: /
#    controller: App\Controller\DefaultController::index
trello:
  path: /api/v1/
  # the controller value has the format 'controller_class::method_name'
  controller: App\Controller\Api\v1\Trello::*